#server:
#  tomcat:
#    max-threads: 1
#    min-spare-threads: 1
#    accept-count: 1
#    max-connections: 1

spring:
  datasource:
    url: jdbc:mysql://gateway.local:3306/benchmark?useSSL=false&characterEncoding=utf8
    username: root
    password: 1234
  redis:
    url: redis://:zC3RBkpdWR@gateway.local:6379
    lettuce:
      pool:
        min-idle: 4
  cache:
    redis:
      time-to-live: 10m


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
